### ISSUE TITLE
Error found in functions.php

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/cw-magazine#13]
Ref: https://wordpress.org/support/topic/error-found-in-functionsphp

In the cw_magazine_php_style() function, the three $site_bg_1 variables are set incorrectly; they reference '../images/', which ends up as an incorrect URL. 

It is lines 521, 555, and 581.

They resolve to domain.com/images/bg-site_color.jpg which doesn't exist, as they're in the theme's images folder.

@ineagu

**Comment by ineagu** [comment]
Looks a quick fix can you take care @hardeep?

**Comment by HardeepAsrani** [comment]
Let me try. @ineagu
